### PR TITLE
Fix CI on PHP 8.0

### PR DESCRIPTION
**Pull request by szepeviktor**
- Put things in chronological order
- Remove dangerous vendor directory caching
- Remove deprecated Composer option

### CODE REVIEW

**Comment by szepeviktor** [comment]
PHPUnit 7 and 8 seem to be incompatible

> Declaration of TheFrosty\WpUtilities\Tests\Plugin\Framework\TestCase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in tests/unit/Plugin/Framework/TestCase.php on line 17

Maybe https://github.com/Yoast/PHPUnit-Polyfill ?

**Comment by thefrosty** [comment]
> PHPUnit 7 and 8 seem to be incompatible
> 
> > Declaration of TheFrosty\WpUtilities\Tests\Plugin\Framework\TestCase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in tests/unit/Plugin/Framework/TestCase.php on line 17
> 
> Maybe https://github.com/Yoast/PHPUnit-Polyfills ?

I have taken a look at that polyfill package before, will take another look.

**Comment by szepeviktor** [comment]
Done 🍏

**Comment by szepeviktor** [comment]
Thank you.

**Pull request merged**
